version: "3.9"

services:
  sistema-pedidos-mysql:
    image: mysql:8.0.33
    container_name: sistema-pedidos-db
    restart: unless-stopped
    tty: true
    ports:
      - "33080:3306"
    environment:
      MYSQL_DATABASE: sistema_pedidos
      MYSQL_USER: sistema_pedidos
      MYSQL_PASSWORD: sistema_pedidos
      MYSQL_ROOT_PASSWORD: rootsql
      SERVICE_NAME: mysql
    networks:
      - sistema-pedidos-network
  sistemapedidos-app:
    build: .
    container_name: sistema-pedidos-app
    ports:
      - "8080:8080"
    depends_on:
      - meudinherim-mysql
    networks:
      - sistema-pedidos-network

networks:
  sistema-pedidos-network:
    driver: bridge
