name: Deployment

on: [push, pull_request]

jobs:
  testes-unitarios:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Executando testes unitários
        run: mvn test -DskipITs=true
